#!/bin/bash
#
# Filename: Refresh Thumbnails
# Date: 2008/02/02 15:10:34
# Licence: GNU GPL
# Dependency: zenity
# Author: Pierre-Yves Landuré <pierre-yves dot landure at biapy.fr>
version='1.0.1'

declare -a thumbnail_paths
thumbnail_paths[0]="${HOME}/.thumbnails"
thumbnail_paths[1]="${HOME}/.cache/thumbnails"

case "${LANG}" in
  'fr' | 'fr_'* )
    err_title="Erreur"
    err_files="Aucun fichier sélectionné"
    info_title="Vignettes effacées"
    info_thumbnails_deleted="|COUNT| vignettes ont été supprimée(s).

Appuyez sur F5 pour rafraîchir l'affichage."
    ;;
  * )
    err_title="Error"
    err_files="No file selected"
    info_title="Thumbnails deleted"
    info_thumbnails_deleted="|COUNT| thumbnails have been deleted.

Hit F5 to refresh display."
    ;;
esac

if [ -z "${1}" ]; then
  zenity --error --title "${err_title}" --text "${err_files}"
  exit 1
fi

delete_count=0
for file_uri in ${NAUTILUS_SCRIPT_SELECTED_URIS[@]}; do

  thumbnail_file="$(echo -n "${file_uri}" \
    | md5sum \
    | cut --delimiter=' ' --fields=1).png"

  for thumbnail_path in ${thumbnail_paths[@]}; do
    if [ -d "${thumbnail_path}" ]; then

      while read -r -d '' found_file; do
        rm "${found_file}";
        delete_count=$((${delete_count} + 1))
      done < <(find "${thumbnail_path}" -type f -name "${thumbnail_file}" -print0)
    fi
  done
done

# This info message is useless and an anoyance.
# zenity --info --title "${info_title}" --text "${info_thumbnails_deleted//|COUNT|/${delete_count}}"

exit 0

