#!/bin/bash
#
# Compute the munin-node total response time
# by timing each installed plugin run.
#

if [ ! -x '/usr/sbin/munin-run' ]; then
  echo "Error: munin-run is not available."
  exit 1
fi

TEMP_FILE="$(command tempfile)"

command find '/etc/munin/plugins/' -mindepth 1 \
    > "${TEMP_FILE}"

RESULT=""
TOTAL_MS="0"
while read PLUGIN; do
  PLUGIN_NAME="$(basename "${PLUGIN}")"
  START_TIME="$(command date +%s%N)"
  command munin-run "${PLUGIN_NAME}" > '/dev/null' 2>&1
  END_TIME="$(command date +%s%N)"

  DURATION_NS="$((${END_TIME} - ${START_TIME}))"
  DURATION_MS="$(command echo "${DURATION_NS}" | command sed -e 's/[0-9]\{6\}$//')"
  TOTAL_MS="$((${TOTAL_MS} + ${DURATION_MS}))"
  RESULT="${RESULT}
$(command printf '%6s ms - %s' "${DURATION_MS}" "${PLUGIN_NAME}")"
done < "${TEMP_FILE}"
command rm "${TEMP_FILE}"
RESULT="${RESULT}
$(command printf '%6s ms - %s\n' "${TOTAL_MS}" "TOTAL")"
echo "${RESULT}" | command sort --numeric-sort --key=1,6

exit 0

