#!/bin/bash
# Check active SSL certificates expiration dates.
# See (fr): https://howto.biapy.com/debian-gnu-linux/serveurs/http/mettre-en-place-une-notification-par-email-de-larrivee-a-expiration-des-certificats-ssl-tls
# See (en): https://howto.biapy.com/en/debian-gnu-linux/servers/http/setup-an-email-alert-on-ssl-tls-certificate-expiration
version="1.1.0"

# Email to witch alerts are sent.
# by default, the root account
alert_email="root"

# Check for ssl-cert-check presence
if type -f 'ssl-cert-check' &>'/dev/null' then
  echo "Error: ssl-cert-check is not available on the system."
  exit 1
fi

apache2_certs=""
if [ -e '/etc/apache2/sites-enabled' ]; then
  apache2_certs="$(grep -r --no-filename 'SSLCertificateFile' '/etc/apache2/sites-enabled/' \
     | egrep -v '#' \
     | sed -e 's/^.*SSLCertificateFile//' -e 's/^[\t ]*["]*//' -e 's/["]*[\t ]*$//')"
fi

lighttpd_certs=""
if [ -e '/etc/lighttpd/conf-enabled' ]; then
  lighttpd_certs="$(grep -r --no-filename 'ssl.pemfile' '/etc/lighttpd/conf-enabled/' \
     | egrep -v '#' \
     | sed -e 's/^.*ssl.pemfile.*=//' -e 's/^[\t ]*["]*//' -e 's/["]*[\t ]*$//')"
fi

cyrus_certs=""
if [ -e '/etc/imapd.conf' -a -e '/etc/cyrus.conf' ]; then
  cyrus_certs="$(grep --no-filename '^tls_cert_file:' '/etc/imapd.conf' \
     | sed -e 's/^.*tls_cert_file://' -e 's/^[\t ]*//' -e 's/[\t ]*$//')"
fi

exim4_certs=""
if [ -d '/etc/exim4' ]; then
  exim4_certs="/etc/exim4/exim.crt
$(grep -r --no-filename '^MAIN_TLS_CERT' '/etc/exim4/' \
     | egrep -v 'CONFDIR' \
     | sed -e 's/^.*MAIN_TLS_CERT.*=//' -e 's/^[\t ]*//' -e 's/[\t ]*$//')"
fi

vsftpd_certs=""
rsa_cert_file=
if [ -e '/etc/vsftpd.conf' ]; then
  vsftpd_certs="$(grep --no-filename '^rsa_cert_file' '/etc/vsftpd.conf' \
     | sed -e 's/^.*rsa_cert_file.*=//' -e 's/^[\t ]*//' -e 's/[\t ]*$//')"
fi

active_certs="$(echo "${apache2_certs}
${lighttpd_certs}
${cyrus_certs}
${exim4_certs}
${vsftpd_certs}" \
    | sed -e '/^$/d' \
    | sort \
    | uniq)"

for cert in ${active_certs}; do
  if [ -e "${cert}" ]; then
    ssl-cert-check -qac "${cert}" -e "${alert_email}"
  fi
done

