#!/bin/bash
# backup-manager-cfis-export
# Copy /var/archives contents to a CFIS (SMBFS) mount point.
#
# @author Pierre-Yves Landuré <pierre-yves.landure@biapy.fr>

NAME="$(command basename "${0}")"
VERSION="1.0.0"

CONFIG_FILE="/etc/backup-manager-cifs-export.conf"

# Fetch parameters from configuration file:
CIFS_MOUNT="$(command grep -e "^CIFS_MOUNT" "${CONFIG_FILE}" | command cut --delimiter="=" --fields=2-)"
CIFS_USER="$(command grep -e "^CIFS_USER" "${CONFIG_FILE}" | command cut --delimiter="=" --fields=2-)"
CIFS_PASSWORD="$(command grep -e "^CIFS_PASSWORD" "${CONFIG_FILE}" | command cut --delimiter="=" --fields=2-)"

if [ -z "${CIFS_MOUNT}" -o -z "${CIFS_USER}" ]; then
  echo "${NAME} - ${VERSION}

Copy /var/archives contents to a CFIS (SMBFS) mount point.

Usage :

  ${NAME}

Configuration :

  The configuration is stored in /etc/backup-manager-cifs-export.conf in this format:

  CIFS_MOUNT=//server/share
  CIFS_USER=domain\user
  CIFS_PASSWORD=password

  Where :
  * CIFS_MOUNT    is the Windows share location.
  * CIFS_USER     is the user login.
  * CIFS_PASSWORD is the user password.
"
  exit 1
fi

# Create a temporary mount point.
MOUNT_LOCATION="$(command mktemp -d -t "tmp.XXXXXXXXXX")"

if command mount --types="cifs" -options="rw,iocharset=iso8859-15,user=${CIFS_USER},password=${CIFS_PASSWORD},async,file_mode=0640,dir_mode=0750" \
    "${CIFS_MOUNT}"  "${MOUNT_LOCATION}"; then

  command rsync --delete --recursive "/var/archives/" "${MOUNT_LOCATION}"

  sleep 5

  if command umount "${MOUNT_LOCATION}"; then
    command rmdir "${MOUNT_LOCATION}"
  else
    echo "Error: unable to unmount '${MOUNT_LOCATION}' from '${CIFS_MOUNT}'." >&2
    exit 1
  fi
else
  command rmdir "${MOUNT_LOCATION}"

  echo "Error: unable to mount '${CIFS_MOUNT}' with user '${CIFS_USER}'." >&2
  exit 1
fi

exit 0
